apiVersion: v1              # Specifies the API version for the PersistentVolume resource
kind: PersistentVolume      # Defines the kind of Kubernetes resource, in this case, a PersistentVolume
metadata:                   # Contains metadata about the PersistentVolume, including its name
  name: mongo-pv
spec:                       # Specifies the desired state of the PersistentVolume
  capacity:                 # Defines the storage capacity of the PersistentVolume
    storage: 256Mi          # Specifies the size of the storage
  accessModes:              # Specifies the supported access modes for the PersistentVolume
    - ReadWriteOnce         # Indicates that the PersistentVolume can be mounted as read-write by a single node
  hostPath:                 # Specifies the type of volume as hostPath and the path on the host machine where the volume is located
    path: /c/Temp/db        # Specifies the path on the host machine where the volume is located, in this case, /tmp/db

# The provided YAML code is a Kubernetes PersistentVolume manifest that defines a PersistentVolume (PV) named mongo-pv using a hostPath volume type
